include $(GOROOT)/src/Make.inc

TARG=send_check

GOFILES=\
				send_check.go\
				checkresult.pb.go


include $(GOROOT)/src/Make.cmd
include $(GOROOT)/src/pkg/goprotobuf.googlecode.com/hg/Make.protobuf
